export const ADD_WISHLIST = "ADD_WISHLIST";
export const ADD_WISHLIST_ASYNC = "ADD_WISHLIST_ASYNC";
export const UPDATE_WISHLIST = "UPDATE_WISHLIST";
export const UPDATE_WISHLIST_ASYNC = "UPDATE_WISHLIST_ASYNC";
export const SAVE_WISHLIST = "SAVE_WISHLIST";
